version: '3.8'

services:
  backend:
    build: ./backend
    container_name: assetflow-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=assetflow_super_secret_jwt_key_for_hackathon
      - JWT_EXPIRES_IN=7d
      - NODE_ENV=production
    volumes:
      - sqlite_data:/app/prisma

  frontend:
    build: ./frontend
    container_name: assetflow-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
